# Travis CI Testing file
# This file will be renamed docker-compose.override.yml
# it will override a standard AzuraCast installation.

version: '2.2'

services:
  cli:
    image: azuracast/azuracast_testing:latest
    volumes:
      - ./:/app
      - composer_data:/tmp
    env_file: azuracast.env
    command: /bin/true

volumes:
  composer_data: {}
