services:
  cli:
    image: swaggerapi/swagger-codegen-cli-v3
    volumes:
      - ./:/api
    networks:
       - azuracast
    command: generate -i http://web/api/openapi.yml -l php -o /api

networks:
  azuracast:
    name: azuracast_azuracast
